### ISSUE TITLE
为什么在提供的数据中只看到equal（E）和replace（R）操作，没有delete（D）、insert（I）操作

### ISSUE THREAD

**Issue by zhentaoCoding** [lipiji/TtT#13]
为什么在提供的数据中只看到equal（E）和replace（R）操作，没有delete（D）、insert（I）操作

**Comment by lipiji** [comment]
@zhentaoCoding 
定长的数据是在开源数据做的，有DI的数据有一部分设计到公司的数据，所以我后面再从重新处理一份放出去。

**Comment by Yang-HangWA** [comment]
@lipiji  请问，数据啥时候能放出来
