### ISSUE TITLE
训练的疑问

### ISSUE THREAD

**Issue by Yang-HangWA** [lipiji/TtT#23]
关于训练有几点疑问：
1.训练中的f1、precision、recall值始终相同，日志显示如下：
`At epoch 3, official dev f1 : 0.819952, precision : 0.819952, recall : 0.819952`

2.训练未设置任何早停终止条件，只是使用num_epochs控制吗，默认的给出的epoch为1000，感觉明显用不到这么大的。
训练到epoch=60，日志就显示三个值都在0.99以上了，如下：
`At epoch 60, official dev f1 : 0.990211, precision : 0.990211, recall : 0.990211`

3.训练数据是否就是项目中给出的这些，还是有些数据需要另外下载呢。

@lipiji   先感谢你的项目分享，也希望你能帮助我。

**Comment by Skywalker-Harrison** [comment]
请问你最后怎么控制停止条件呢? 还有感觉0.99也太高了. 这是什么含义呢?
