### ISSUE TITLE
没有很理解的一个问题是，对于测试数据来说是不应该知道target句子长度的，那这个时候怎么进行target句子生成的呢？

### ISSUE THREAD

**Issue by bing170215** [lipiji/TtT#6]
没有很理解的一个问题是，对于测试数据来说是不应该知道target句子长度的，那这个时候怎么进行target句子生成的呢？因为我看论文中提到，针对source句子与target句子不同的长度，会对句子进行不同的预处理，可是真实情况进行语法纠错的时候是不知道target句子长度的，所以请问一下这个时候怎么处理。谢谢回答

**Comment by lipiji** [comment]
测试时候考虑到语法纠错一般不会有太大的 长度变化，可以补充3~5个mask符号进行试验。

**Comment by bing170215** [comment]
好的谢谢
