### ISSUE TITLE
请问是否可以提供一个数据sample

### ISSUE THREAD

**Issue by YouranShan** [lipiji/TtT#7]
请问是否可以提供一个数据sample
1. DataLoader里面需要的数据是由\t分割的三段文本，但source和target只有两段，而第三段也没有在后续代码中出现，是不是应该把断言那里改成2
2. tag_name_list在一开始出现就加了一个sep，而后面的条件判断中又为tag_name_list添加了sep，这应当是冗余了吧？

**Comment by yiweiyihang** [comment]
+1 求问HybirdSet转换后的数据格式是什么样的

**Comment by bing170215** [comment]
第二个问题，我也觉得是冗余了

**Comment by lipiji** [comment]
见data文件夹
